ThemeDescription="KDE Breeze based theme"

ThemeAuthor="ItzSelenux"
Look=flat
RolloverButtonsSupported=1
TitleBarHeight=26
TitleBarJustify=1

TitleButtonsLeft="s"
TitleButtonsRight="xmi"
TitleButtonsSupported="sxmi"

BorderSizeX=4
BorderSizeY=4
DlgBorderSizeX=2
DlgBorderSizeY=2

ColorNormalBorder="rgb:2a/2d/32"
ColorActiveBorder="rgb:2a/2d/32"
ColorActiveTitleBar="rgb:31/36/3b"
ColorNormalTitleBar="rgb:31/36/3b"
ColorNormalButton="rgb:2a/2d/32"
ColorNormalTitleBarText="rgb:ff/ff/ff"
ColorActiveTitleBarText="rgb:ff/ff/ff"
ColorNormalMenu="rgb:2a/2d/32"
ColorActiveMenuItem="rgb:31/67/83"
ColorNormalMenuItemText="rgb:ff/ff/ff"
ColorActiveMenuItemText="rgb:ff/ff/ff"
ColorDisabledMenuItemText="rgb:80/80/80"
ColorMoveSizeStatus="rgb:2a/2d/32"
ColorMoveSizeStatusText="rgb:FF/FF/FF"

ColorInputSelection="rgb:31/67/83"
ColorInputSelectionText="rgb:c6/c6/c6"
#taskbar parameters
ColorDefaultTaskBar="rgb:2a/2d/32"
ColorNormalTaskBarApp="rgb:2a/2d/32"
ColorNormalTaskBarAppText="rgb:2a/2d/32"
ColorActiveTaskBarApp="rgb:31/67/83"
ColorActiveTaskBarAppText="rgb:31/67/83"
ColorMinimizedTaskBarApp="rgb:2a/2d/32"
ColorMinimizedTaskBarAppText="rgb:2a/2d/32"
ColorInvisibleTaskBarApp="rgb:1a/1a/1a"
ColorInput="rgb:2a/2d/32"
ColorInputText="rgb:c6/c6/c6"
#listbox
ColorListBox="rgb:2a/2d/32"
ColorListBoxText="rgb:c6/c6/c6"
ColorListBoxSelection="rgb:31/67/83"
ColorListBoxSelectionText="rgb:c6/c6/c6"
#Workspaces
ColorActiveWorkspaceButton="rgb:31/67/83"
ColorActiveWorkspaceButtonText="rgb:c6/c6/c6"

#Dialog box
ColorDialog="rgb:2a/2d/32"
ColorNormalButtonText="rgb:ff/ff/ff"


#Tooltip text
ColorToolTip="rgb:2a/2d/32"
ColorToolTipText="rgb:ff/ff/FF"
#scrollbar
ColorScrollBar="rgb:2a/2d/32"
ColorScrollBarSlider="rgb:26/26/26"
ColorScrollBarButtonArrow="rgb:2a/2d/32"
#Quick switch
ColorQuickSwitch="rgb:2a/2d/32"
ColorQuickSwitchActive="rgb:31/67/83"
ColorQuickSwitchText="rgb:FF/FF/FF"
ColorClock="rgb:2a/2d/32"
ColorClockText="rgb:ff/ff/ff"
SmallIconSize=16
ActiveTaskBarFontNameXft   =    "Snap:size=0,sans-serif:size=0:bold"
NormalTaskBarFontNameXft   =    "Snap:size=0,sans-serif:size=0"
TaskBarShowAllWindows=1
#background parameters
DesktopBackgroundCenter=0
DesktopBackgroundScaled=1
DesktopBackgroundImage="charlie-henson.png"
