ThemeDescription="KDE Breeze based theme"

ThemeAuthor="ItzSelenux"
Look=flat
RolloverButtonsSupported=1
TitleBarHeight=26
TitleBarJustify=50

TitleButtonsLeft="s"
TitleButtonsRight="xmi"
TitleButtonsSupported="sxmi"

BorderSizeX=4
BorderSizeY=4
DlgBorderSizeX=2
DlgBorderSizeY=2

ColorNormalBorder="rgb:2a/2d/32"
ColorActiveBorder="rgb:2a/2d/32"
ColorActiveTitleBar="rgb:31/36/3b"
ColorNormalTitleBar="rgb:31/36/3b"
ColorNormalButton="rgb:2a/2d/32"
ColorNormalTitleBarText="rgb:ff/ff/ff"
ColorActiveTitleBarText="rgb:ff/ff/ff"
ColorNormalMenu="rgb:2a/2d/32"
ColorActiveMenuItem="rgb:31/67/83"
ColorNormalMenuItemText="rgb:ff/ff/ff"
ColorActiveMenuItemText="rgb:ff/ff/ff"
ColorDisabledMenuItemText="rgb:80/80/80"
ColorMoveSizeStatus="rgb:31/67/83"
ColorMoveSizeStatusText="rgb:FF/FF/FF"

ColorInputSelection="rgb:31/67/83"
#taskbar parameters
ColorDefaultTaskBar="rgb:2a/2d/32"
ColorNormalTaskBarApp="rgb:2a/2d/32"
ColorNormalTaskBarAppText="rgb:ff/ff/ff"
ColorActiveTaskBarApp="rgb:31/67/83"
ColorActiveTaskBarAppText="rgb:ff/ff/ff"
ColorMinimizedTaskBarApp="rgb:2a/2d/32"
ColorMinimizedTaskBarAppText="rgb:b3/b3/b3"
#listbox
ColorListBox="rgb:CC/CC/CC"
ColorListBoxText="rgb:00/00/00"
ColorListBoxSelection="rgb:CC/CC/FF"
ColorListBoxSelectionText="rgb:00/00/00"
#Dialog box
ColorDialog="rgb:2a/2d/32"
#Tooltip text
ColorToolTip="rgb:2a/2d/32"
ColorToolTipText="rgb:ff/ff/FF"
#scrollbar
ColorScrollBar="rgb:C0/C0/C0"
ColorScrollBarSlider="rgb:C0/C0/C0"
ColorScrollBarButtonArrow="rgb:C0/C0/C0"
#Quick switch
ColorQuickSwitch="rgb:2a/2d/32"
ColorQuickSwitchActive="rgb:31/67/83"
ColorQuickSwitchText="rgb:FF/FF/FF"
ColorClock="rgb:2a/2d/32"
ColorClockText="rgb:ff/ff/ff"
SmallIconSize=32
#background parameters
DesktopBackgroundCenter=0
DesktopBackgroundScaled=1
DesktopBackgroundImage="charlie-henson.png"
